name: medical
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.0
  flutter_svg: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - images/search1.svg
    - images/search2.svg
    - images/eventsIcon1.svg
    - images/eventsIcon2.svg
    - images/DirectoruIcon1.svg
    - images/DirectoruIcon2.svg
    - images/MoreIcon1.svg
    - images/MoreIcon2.svg
    - images/HomeIcon1.svg
    - images/HomeIcon2.svg
    - images/equalizerIcon.svg
    - images/megaphone.svg
    - images/heart.svg
    - images/alarm.svg
    - images/patient.jpg
    - images/annoncements.jpg